name: prod
variables:
  - name: baseUrl
    value: https://ngekos.mauln.dev/api/v1
  - name: unprotected
    value: /BqSEOywguVg5llYm22
  - name: protected
    value: /1zCg1406d2x331wM
  - name: token
    value: ""
